name: Keep Render App Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping-render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Render App
        run: curl -s https://polling-app-gleq.onrender.com/health
